namespace CapaPresentacion
{
    partial class Form4
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form4));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuDataGridView1 = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.idp = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label1 = new System.Windows.Forms.Label();
            this.bunifuDatePicker2 = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.bunifuPictureBox2 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.editp = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.cantidadp = new Bunifu.UI.WinForms.BunifuTextBox();
            this.preciop = new Bunifu.UI.WinForms.BunifuTextBox();
            this.nombrep = new Bunifu.UI.WinForms.BunifuTextBox();
            this.mproductos = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuDataGridView1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox2)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuDataGridView1
            // 
            this.bunifuDataGridView1.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.bunifuDataGridView1.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.bunifuDataGridView1.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.bunifuDataGridView1.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.bunifuDataGridView1.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.bunifuDataGridView1.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.bunifuDataGridView1.ColumnHeadersHeight = 40;
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.Name = null;
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.bunifuDataGridView1.DefaultCellStyle = dataGridViewCellStyle3;
            this.bunifuDataGridView1.EnableHeadersVisualStyles = false;
            this.bunifuDataGridView1.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.bunifuDataGridView1.HeaderBgColor = System.Drawing.Color.Empty;
            this.bunifuDataGridView1.HeaderForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.Location = new System.Drawing.Point(94, 350);
            this.bunifuDataGridView1.Name = "bunifuDataGridView1";
            this.bunifuDataGridView1.RowHeadersVisible = false;
            this.bunifuDataGridView1.RowTemplate.Height = 40;
            this.bunifuDataGridView1.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.bunifuDataGridView1.Size = new System.Drawing.Size(704, 196);
            this.bunifuDataGridView1.TabIndex = 34;
            this.bunifuDataGridView1.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // idp
            // 
            this.idp.AcceptsReturn = false;
            this.idp.AcceptsTab = false;
            this.idp.AnimationSpeed = 200;
            this.idp.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.idp.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.idp.AutoSizeHeight = true;
            this.idp.BackColor = System.Drawing.Color.Transparent;
            this.idp.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("idp.BackgroundImage")));
            this.idp.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.idp.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.idp.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.idp.BorderColorIdle = System.Drawing.Color.Silver;
            this.idp.BorderRadius = 1;
            this.idp.BorderThickness = 1;
            this.idp.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.idp.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.idp.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.idp.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.idp.DefaultText = "";
            this.idp.FillColor = System.Drawing.Color.White;
            this.idp.HideSelection = true;
            this.idp.IconLeft = null;
            this.idp.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.idp.IconPadding = 10;
            this.idp.IconRight = null;
            this.idp.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.idp.Lines = new string[0];
            this.idp.Location = new System.Drawing.Point(114, 213);
            this.idp.MaxLength = 32767;
            this.idp.MinimumSize = new System.Drawing.Size(1, 1);
            this.idp.Modified = false;
            this.idp.Multiline = false;
            this.idp.Name = "idp";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.idp.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.idp.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.idp.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.idp.OnIdleState = stateProperties4;
            this.idp.Padding = new System.Windows.Forms.Padding(3);
            this.idp.PasswordChar = '\0';
            this.idp.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.idp.PlaceholderText = "ID";
            this.idp.ReadOnly = false;
            this.idp.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.idp.SelectedText = "";
            this.idp.SelectionLength = 0;
            this.idp.SelectionStart = 0;
            this.idp.ShortcutsEnabled = true;
            this.idp.Size = new System.Drawing.Size(63, 54);
            this.idp.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.idp.TabIndex = 33;
            this.idp.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.idp.TextMarginBottom = 0;
            this.idp.TextMarginLeft = 3;
            this.idp.TextMarginTop = 1;
            this.idp.TextPlaceholder = "ID";
            this.idp.UseSystemPasswordChar = false;
            this.idp.WordWrap = true;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Segoe UI", 48F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ImageAlign = System.Drawing.ContentAlignment.TopRight;
            this.label1.Location = new System.Drawing.Point(225, 47);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(565, 86);
            this.label1.TabIndex = 32;
            this.label1.Text = "Edit your product";
            // 
            // bunifuDatePicker2
            // 
            this.bunifuDatePicker2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuDatePicker2.BorderColor = System.Drawing.Color.Silver;
            this.bunifuDatePicker2.BorderRadius = 1;
            this.bunifuDatePicker2.Color = System.Drawing.Color.Silver;
            this.bunifuDatePicker2.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.bunifuDatePicker2.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.bunifuDatePicker2.DisabledColor = System.Drawing.Color.Gray;
            this.bunifuDatePicker2.DisplayWeekNumbers = false;
            this.bunifuDatePicker2.DPHeight = 0;
            this.bunifuDatePicker2.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.bunifuDatePicker2.FillDatePicker = false;
            this.bunifuDatePicker2.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuDatePicker2.ForeColor = System.Drawing.Color.Black;
            this.bunifuDatePicker2.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuDatePicker2.Icon")));
            this.bunifuDatePicker2.IconColor = System.Drawing.Color.Gray;
            this.bunifuDatePicker2.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.bunifuDatePicker2.LeftTextMargin = 5;
            this.bunifuDatePicker2.Location = new System.Drawing.Point(380, 296);
            this.bunifuDatePicker2.MinimumSize = new System.Drawing.Size(4, 32);
            this.bunifuDatePicker2.Name = "bunifuDatePicker2";
            this.bunifuDatePicker2.Size = new System.Drawing.Size(252, 32);
            this.bunifuDatePicker2.TabIndex = 31;
            // 
            // bunifuPictureBox2
            // 
            this.bunifuPictureBox2.AllowFocused = false;
            this.bunifuPictureBox2.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox2.AutoSizeHeight = true;
            this.bunifuPictureBox2.BorderRadius = 0;
            this.bunifuPictureBox2.Image = ((System.Drawing.Image)(resources.GetObject("bunifuPictureBox2.Image")));
            this.bunifuPictureBox2.IsCircle = true;
            this.bunifuPictureBox2.Location = new System.Drawing.Point(94, 26);
            this.bunifuPictureBox2.Name = "bunifuPictureBox2";
            this.bunifuPictureBox2.Size = new System.Drawing.Size(134, 134);
            this.bunifuPictureBox2.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox2.TabIndex = 30;
            this.bunifuPictureBox2.TabStop = false;
            this.bunifuPictureBox2.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Square;
            // 
            // editp
            // 
            this.editp.AllowAnimations = true;
            this.editp.AllowMouseEffects = true;
            this.editp.AllowToggling = false;
            this.editp.AnimationSpeed = 200;
            this.editp.AutoGenerateColors = false;
            this.editp.AutoRoundBorders = false;
            this.editp.AutoSizeLeftIcon = true;
            this.editp.AutoSizeRightIcon = true;
            this.editp.BackColor = System.Drawing.Color.Transparent;
            this.editp.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.editp.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("editp.BackgroundImage")));
            this.editp.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.editp.ButtonText = "Edit Product";
            this.editp.ButtonTextMarginLeft = 0;
            this.editp.ColorContrastOnClick = 45;
            this.editp.ColorContrastOnHover = 45;
            this.editp.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.editp.CustomizableEdges = borderEdges1;
            this.editp.DialogResult = System.Windows.Forms.DialogResult.None;
            this.editp.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.editp.DisabledFillColor = System.Drawing.Color.Empty;
            this.editp.DisabledForecolor = System.Drawing.Color.Empty;
            this.editp.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.editp.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.editp.ForeColor = System.Drawing.Color.White;
            this.editp.IconLeft = null;
            this.editp.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.editp.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.editp.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.editp.IconMarginLeft = 11;
            this.editp.IconPadding = 10;
            this.editp.IconRight = null;
            this.editp.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.editp.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.editp.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.editp.IconSize = 25;
            this.editp.IdleBorderColor = System.Drawing.Color.Empty;
            this.editp.IdleBorderRadius = 0;
            this.editp.IdleBorderThickness = 0;
            this.editp.IdleFillColor = System.Drawing.Color.Empty;
            this.editp.IdleIconLeftImage = null;
            this.editp.IdleIconRightImage = null;
            this.editp.IndicateFocus = false;
            this.editp.Location = new System.Drawing.Point(657, 552);
            this.editp.Name = "editp";
            this.editp.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.editp.OnDisabledState.BorderRadius = 1;
            this.editp.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.editp.OnDisabledState.BorderThickness = 1;
            this.editp.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.editp.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.editp.OnDisabledState.IconLeftImage = null;
            this.editp.OnDisabledState.IconRightImage = null;
            this.editp.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.editp.onHoverState.BorderRadius = 1;
            this.editp.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.editp.onHoverState.BorderThickness = 1;
            this.editp.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.editp.onHoverState.ForeColor = System.Drawing.Color.White;
            this.editp.onHoverState.IconLeftImage = null;
            this.editp.onHoverState.IconRightImage = null;
            this.editp.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.editp.OnIdleState.BorderRadius = 1;
            this.editp.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.editp.OnIdleState.BorderThickness = 1;
            this.editp.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.editp.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.editp.OnIdleState.IconLeftImage = null;
            this.editp.OnIdleState.IconRightImage = null;
            this.editp.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.editp.OnPressedState.BorderRadius = 1;
            this.editp.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.editp.OnPressedState.BorderThickness = 1;
            this.editp.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.editp.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.editp.OnPressedState.IconLeftImage = null;
            this.editp.OnPressedState.IconRightImage = null;
            this.editp.Size = new System.Drawing.Size(141, 42);
            this.editp.TabIndex = 29;
            this.editp.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.editp.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.editp.TextMarginLeft = 0;
            this.editp.TextPadding = new System.Windows.Forms.Padding(0);
            this.editp.UseDefaultRadiusAndThickness = true;
            this.editp.Click += new System.EventHandler(this.editp_Click);
            // 
            // cantidadp
            // 
            this.cantidadp.AcceptsReturn = false;
            this.cantidadp.AcceptsTab = false;
            this.cantidadp.AnimationSpeed = 200;
            this.cantidadp.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.cantidadp.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.cantidadp.AutoSizeHeight = true;
            this.cantidadp.BackColor = System.Drawing.Color.Transparent;
            this.cantidadp.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("cantidadp.BackgroundImage")));
            this.cantidadp.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.cantidadp.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cantidadp.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.cantidadp.BorderColorIdle = System.Drawing.Color.Silver;
            this.cantidadp.BorderRadius = 1;
            this.cantidadp.BorderThickness = 1;
            this.cantidadp.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.cantidadp.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.cantidadp.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.cantidadp.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.cantidadp.DefaultText = "";
            this.cantidadp.FillColor = System.Drawing.Color.White;
            this.cantidadp.HideSelection = true;
            this.cantidadp.IconLeft = null;
            this.cantidadp.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.cantidadp.IconPadding = 10;
            this.cantidadp.IconRight = null;
            this.cantidadp.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.cantidadp.Lines = new string[0];
            this.cantidadp.Location = new System.Drawing.Point(114, 283);
            this.cantidadp.MaxLength = 32767;
            this.cantidadp.MinimumSize = new System.Drawing.Size(1, 1);
            this.cantidadp.Modified = false;
            this.cantidadp.Multiline = false;
            this.cantidadp.Name = "cantidadp";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cantidadp.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.cantidadp.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cantidadp.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cantidadp.OnIdleState = stateProperties8;
            this.cantidadp.Padding = new System.Windows.Forms.Padding(3);
            this.cantidadp.PasswordChar = '\0';
            this.cantidadp.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.cantidadp.PlaceholderText = "Cantidad";
            this.cantidadp.ReadOnly = false;
            this.cantidadp.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.cantidadp.SelectedText = "";
            this.cantidadp.SelectionLength = 0;
            this.cantidadp.SelectionStart = 0;
            this.cantidadp.ShortcutsEnabled = true;
            this.cantidadp.Size = new System.Drawing.Size(252, 54);
            this.cantidadp.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.cantidadp.TabIndex = 28;
            this.cantidadp.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.cantidadp.TextMarginBottom = 0;
            this.cantidadp.TextMarginLeft = 3;
            this.cantidadp.TextMarginTop = 1;
            this.cantidadp.TextPlaceholder = "Cantidad";
            this.cantidadp.UseSystemPasswordChar = false;
            this.cantidadp.WordWrap = true;
            // 
            // preciop
            // 
            this.preciop.AcceptsReturn = false;
            this.preciop.AcceptsTab = false;
            this.preciop.AnimationSpeed = 200;
            this.preciop.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.preciop.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.preciop.AutoSizeHeight = true;
            this.preciop.BackColor = System.Drawing.Color.Transparent;
            this.preciop.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("preciop.BackgroundImage")));
            this.preciop.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.preciop.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.preciop.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.preciop.BorderColorIdle = System.Drawing.Color.Silver;
            this.preciop.BorderRadius = 1;
            this.preciop.BorderThickness = 1;
            this.preciop.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.preciop.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.preciop.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.preciop.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.preciop.DefaultText = "";
            this.preciop.FillColor = System.Drawing.Color.White;
            this.preciop.HideSelection = true;
            this.preciop.IconLeft = null;
            this.preciop.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.preciop.IconPadding = 10;
            this.preciop.IconRight = null;
            this.preciop.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.preciop.Lines = new string[0];
            this.preciop.Location = new System.Drawing.Point(483, 213);
            this.preciop.MaxLength = 32767;
            this.preciop.MinimumSize = new System.Drawing.Size(1, 1);
            this.preciop.Modified = false;
            this.preciop.Multiline = false;
            this.preciop.Name = "preciop";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.preciop.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.preciop.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.preciop.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.preciop.OnIdleState = stateProperties12;
            this.preciop.Padding = new System.Windows.Forms.Padding(3);
            this.preciop.PasswordChar = '\0';
            this.preciop.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.preciop.PlaceholderText = "Precio";
            this.preciop.ReadOnly = false;
            this.preciop.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.preciop.SelectedText = "";
            this.preciop.SelectionLength = 0;
            this.preciop.SelectionStart = 0;
            this.preciop.ShortcutsEnabled = true;
            this.preciop.Size = new System.Drawing.Size(252, 54);
            this.preciop.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.preciop.TabIndex = 27;
            this.preciop.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.preciop.TextMarginBottom = 0;
            this.preciop.TextMarginLeft = 3;
            this.preciop.TextMarginTop = 1;
            this.preciop.TextPlaceholder = "Precio";
            this.preciop.UseSystemPasswordChar = false;
            this.preciop.WordWrap = true;
            // 
            // nombrep
            // 
            this.nombrep.AcceptsReturn = false;
            this.nombrep.AcceptsTab = false;
            this.nombrep.AnimationSpeed = 200;
            this.nombrep.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.nombrep.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.nombrep.AutoSizeHeight = true;
            this.nombrep.BackColor = System.Drawing.Color.Transparent;
            this.nombrep.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("nombrep.BackgroundImage")));
            this.nombrep.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.nombrep.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.nombrep.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.nombrep.BorderColorIdle = System.Drawing.Color.Silver;
            this.nombrep.BorderRadius = 1;
            this.nombrep.BorderThickness = 1;
            this.nombrep.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.nombrep.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.nombrep.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.nombrep.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.nombrep.DefaultText = "";
            this.nombrep.FillColor = System.Drawing.Color.White;
            this.nombrep.HideSelection = true;
            this.nombrep.IconLeft = null;
            this.nombrep.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.nombrep.IconPadding = 10;
            this.nombrep.IconRight = null;
            this.nombrep.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.nombrep.Lines = new string[0];
            this.nombrep.Location = new System.Drawing.Point(207, 213);
            this.nombrep.MaxLength = 32767;
            this.nombrep.MinimumSize = new System.Drawing.Size(1, 1);
            this.nombrep.Modified = false;
            this.nombrep.Multiline = false;
            this.nombrep.Name = "nombrep";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nombrep.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.nombrep.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nombrep.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nombrep.OnIdleState = stateProperties16;
            this.nombrep.Padding = new System.Windows.Forms.Padding(3);
            this.nombrep.PasswordChar = '\0';
            this.nombrep.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.nombrep.PlaceholderText = "Nombre del producto";
            this.nombrep.ReadOnly = false;
            this.nombrep.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.nombrep.SelectedText = "";
            this.nombrep.SelectionLength = 0;
            this.nombrep.SelectionStart = 0;
            this.nombrep.ShortcutsEnabled = true;
            this.nombrep.Size = new System.Drawing.Size(252, 54);
            this.nombrep.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.nombrep.TabIndex = 26;
            this.nombrep.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.nombrep.TextMarginBottom = 0;
            this.nombrep.TextMarginLeft = 3;
            this.nombrep.TextMarginTop = 1;
            this.nombrep.TextPlaceholder = "Nombre del producto";
            this.nombrep.UseSystemPasswordChar = false;
            this.nombrep.WordWrap = true;
            // 
            // mproductos
            // 
            this.mproductos.AllowAnimations = true;
            this.mproductos.AllowMouseEffects = true;
            this.mproductos.AllowToggling = false;
            this.mproductos.AnimationSpeed = 200;
            this.mproductos.AutoGenerateColors = false;
            this.mproductos.AutoRoundBorders = false;
            this.mproductos.AutoSizeLeftIcon = true;
            this.mproductos.AutoSizeRightIcon = true;
            this.mproductos.BackColor = System.Drawing.Color.Transparent;
            this.mproductos.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.mproductos.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("mproductos.BackgroundImage")));
            this.mproductos.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.mproductos.ButtonText = "Mostrar Productos";
            this.mproductos.ButtonTextMarginLeft = 0;
            this.mproductos.ColorContrastOnClick = 45;
            this.mproductos.ColorContrastOnHover = 45;
            this.mproductos.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.mproductos.CustomizableEdges = borderEdges2;
            this.mproductos.DialogResult = System.Windows.Forms.DialogResult.None;
            this.mproductos.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.mproductos.DisabledFillColor = System.Drawing.Color.Empty;
            this.mproductos.DisabledForecolor = System.Drawing.Color.Empty;
            this.mproductos.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.mproductos.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.mproductos.ForeColor = System.Drawing.Color.White;
            this.mproductos.IconLeft = null;
            this.mproductos.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.mproductos.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.mproductos.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.mproductos.IconMarginLeft = 11;
            this.mproductos.IconPadding = 10;
            this.mproductos.IconRight = null;
            this.mproductos.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.mproductos.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.mproductos.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.mproductos.IconSize = 25;
            this.mproductos.IdleBorderColor = System.Drawing.Color.Empty;
            this.mproductos.IdleBorderRadius = 0;
            this.mproductos.IdleBorderThickness = 0;
            this.mproductos.IdleFillColor = System.Drawing.Color.Empty;
            this.mproductos.IdleIconLeftImage = null;
            this.mproductos.IdleIconRightImage = null;
            this.mproductos.IndicateFocus = false;
            this.mproductos.Location = new System.Drawing.Point(503, 552);
            this.mproductos.Name = "mproductos";
            this.mproductos.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.mproductos.OnDisabledState.BorderRadius = 1;
            this.mproductos.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.mproductos.OnDisabledState.BorderThickness = 1;
            this.mproductos.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.mproductos.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.mproductos.OnDisabledState.IconLeftImage = null;
            this.mproductos.OnDisabledState.IconRightImage = null;
            this.mproductos.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.mproductos.onHoverState.BorderRadius = 1;
            this.mproductos.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.mproductos.onHoverState.BorderThickness = 1;
            this.mproductos.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.mproductos.onHoverState.ForeColor = System.Drawing.Color.White;
            this.mproductos.onHoverState.IconLeftImage = null;
            this.mproductos.onHoverState.IconRightImage = null;
            this.mproductos.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.mproductos.OnIdleState.BorderRadius = 1;
            this.mproductos.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.mproductos.OnIdleState.BorderThickness = 1;
            this.mproductos.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.mproductos.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.mproductos.OnIdleState.IconLeftImage = null;
            this.mproductos.OnIdleState.IconRightImage = null;
            this.mproductos.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.mproductos.OnPressedState.BorderRadius = 1;
            this.mproductos.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.mproductos.OnPressedState.BorderThickness = 1;
            this.mproductos.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.mproductos.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.mproductos.OnPressedState.IconLeftImage = null;
            this.mproductos.OnPressedState.IconRightImage = null;
            this.mproductos.Size = new System.Drawing.Size(129, 42);
            this.mproductos.TabIndex = 35;
            this.mproductos.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.mproductos.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.mproductos.TextMarginLeft = 0;
            this.mproductos.TextPadding = new System.Windows.Forms.Padding(0);
            this.mproductos.UseDefaultRadiusAndThickness = true;
            this.mproductos.Click += new System.EventHandler(this.mproductos_Click);
            // 
            // Form4
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(893, 620);
            this.Controls.Add(this.mproductos);
            this.Controls.Add(this.bunifuDataGridView1);
            this.Controls.Add(this.idp);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.bunifuDatePicker2);
            this.Controls.Add(this.bunifuPictureBox2);
            this.Controls.Add(this.editp);
            this.Controls.Add(this.cantidadp);
            this.Controls.Add(this.preciop);
            this.Controls.Add(this.nombrep);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.SizableToolWindow;
            this.Name = "Form4";
            this.Text = "Form4";
            ((System.ComponentModel.ISupportInitialize)(this.bunifuDataGridView1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox2)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuDataGridView bunifuDataGridView1;
        private Bunifu.UI.WinForms.BunifuTextBox idp;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuDatePicker bunifuDatePicker2;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton editp;
        private Bunifu.UI.WinForms.BunifuTextBox cantidadp;
        private Bunifu.UI.WinForms.BunifuTextBox preciop;
        private Bunifu.UI.WinForms.BunifuTextBox nombrep;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton mproductos;
    }
}